### ISSUE TITLE
How to use this model for data without class labels?

### ISSUE THREAD

**Issue by 314rated** [dashayushman/TAC-GAN#7]
Hi,
If we just have image-text pairs without classlabels, what all changes do you suggest to run on such a dataset? Also, would the results be vastly affected without class labels?

Thanks!

**Comment by dashayushman** [comment]
Hi,

I would suggest you to follow https://arxiv.org/abs/1710.10916

I think this is exactly what you want :) hope it helps

**Comment by 314rated** [comment]
Thanks for the response!
